### ISSUE TITLE
What version of Pangolin did you use ?

### ISSUE THREAD

**Issue by ghost** [uoip/stereo_ptam#5]
Hello, what version of Pangolin did you use:
https://github.com/stevenlovegrove/Pangolin or https://github.com/uoip/pangolin
Thank you

**Comment by ngthanhtin** [comment]
I have built successfully with https://github.com/stevenlovegrove/Pangolin. Those who download the repo should change the name from "Pangolin" to "pangolin", this will fix errors when you make --build .
